"""Pack the audio analysis into js/track-data.js for the player.

Inputs (tools/analysis/):
  bt_beats.npy / bt_downbeats.npy  beat + downbeat times (beat_this)
  feat_u8.npy                      60 fps features: kick, snare, hat, bass, vox, rms, 16 log bands
  kick_events.npy / snare_events.npy  onset events [time, strength]
  lyrics_timed2.json               lyric lines with word times (see align/merge/snap scripts)
"""
import json, base64, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
A = os.path.join(HERE, 'analysis')
OUT = os.path.join(HERE, '..', 'js', 'track-data.js')

beats = np.load(os.path.join(A, 'bt_beats.npy'))
downbeats = np.load(os.path.join(A, 'bt_downbeats.npy'))
downbeats = downbeats[downbeats > 0.2]          # drop the spurious t=0 downbeat
feat = np.load(os.path.join(A, 'feat_u8.npy'))
kicks = np.load(os.path.join(A, 'kick_events.npy'))
snares = np.load(os.path.join(A, 'snare_events.npy'))
lyr = json.load(open(os.path.join(A, 'lyrics_timed2.json')))

# Section map (musical boundaries picked from downbeats + lyric onsets + novelty peaks)
SECTIONS = [
    ('intro', 0.00, 18.64), ('verse1', 18.64, 45.12), ('pre1', 45.12, 51.74),
    ('chorus1', 51.74, 73.16), ('post1', 73.16, 81.38), ('verse2', 81.38, 108.90),
    ('pre2', 108.90, 115.84), ('chorus2', 115.84, 137.90), ('bridge', 137.90, 166.44),
    ('breakdown', 166.44, 182.64), ('final', 182.64, 204.42), ('outro', 204.42, 226.0),
]

lines = []
sec = None
for L in lyr:
    if 'section' in L:
        sec = L['section']; continue
    lines.append({
        'sec': sec, 'text': L['text'], 's': round(L['start'], 3), 'e': round(L['end'], 3),
        'w': [[w['w'], round(w['s'], 3), round(w['e'], 3)] for w in L['words']],
    })

data = {
    'duration': 226.0,
    'fps': 60,
    'featNames': ['kick', 'snare', 'hat', 'bass', 'vox', 'rms'] + [f'b{i}' for i in range(16)],
    'featStride': int(feat.shape[1]),
    'featFrames': int(feat.shape[0]),
    'feat': base64.b64encode(feat.astype(np.uint8).tobytes()).decode(),
    'beats': [round(float(b), 3) for b in beats],
    'downbeats': [round(float(b), 3) for b in downbeats],
    'kicks': [[round(float(t), 3), round(float(v), 2)] for t, v in kicks],
    'snares': [[round(float(t), 3), round(float(v), 2)] for t, v in snares],
    'sections': [{'name': n, 's': s, 'e': e} for n, s, e in SECTIONS],
    'lines': lines,
}
with open(OUT, 'w') as f:
    f.write('// Generated by tools/build_track_data.py — do not edit by hand.\n')
    f.write('window.TRACK = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('wrote', OUT, os.path.getsize(OUT), 'bytes')
