/* Generated by tools/analysis/make_timing.py — do not edit by hand.
 * Word timings: Whisper (large-v3-turbo) on a Demucs vocal stem, checked by hand (tools/analysis/lyrics.json).
 */
(function (RV) {
  'use strict';
  RV.DURATION = 27.960;
  RV.LYRICS = [
    { s: "intro", t0: 0.02, t1: 0.32, text: "Bum!", w: [[0.02,0.32,"Bum!"]] },
    { s: "verse", t0: 0.75, t1: 1.98, text: "Food is yummy", w: [[0.75,0.99,"Food"],[0.99,1.18,"is"],[1.18,1.98,"yummy,"]] },
    { s: "verse", t0: 2.02, t1: 2.67, text: "bum ba ba bum", w: [[2.02,2.18,"bum"],[2.18,2.33,"ba"],[2.33,2.50,"ba"],[2.50,2.67,"bum"]] },
    { s: "verse", t0: 2.92, t1: 6.36, text: "It tastes good like that old thing in the cupboard", w: [[2.92,3.18,"It"],[3.18,3.58,"tastes"],[3.58,3.82,"good"],[3.82,4.22,"like"],[4.22,4.56,"that"],[4.56,4.90,"old"],[4.90,5.22,"thing"],[5.22,5.56,"in"],[5.56,5.84,"the"],[5.84,6.36,"cupboard"]] },
    { s: "scat", t0: 6.52, t1: 8.30, text: "dun da-da dun, da-da dun", w: [[6.52,6.95,"dun"],[7.02,7.40,"da-da"],[7.42,7.62,"dun,"],[7.64,7.96,"da-da"],[7.98,8.30,"dun!"]] },
    { s: "chorus", t0: 8.62, t1: 11.05, text: "I eat every day", w: [[8.62,8.92,"I"],[8.92,10.03,"eat"],[10.03,10.55,"every"],[10.55,11.05,"day"]] },
    { s: "chorus", t0: 11.30, t1: 13.69, text: "a-a-a a-a-a aaay!", w: [[11.30,12.00,"a-a-a"],[12.02,12.77,"a-a-a"],[12.79,13.69,"aaay!"]] },
    { s: "chorus", t0: 13.69, t1: 15.99, text: "a-a-AY, ay!", w: [[13.69,14.58,"a-a-"],[14.58,15.30,"AY,"],[15.30,15.99,"ay!"]] },
    { s: "chorus", t0: 16.03, t1: 16.98, text: "Yum in my tum", w: [[16.03,16.31,"Yum"],[16.34,16.50,"in"],[16.52,16.67,"my"],[16.68,16.98,"tum,"]] },
    { s: "chorus", t0: 17.06, t1: 18.76, text: "hip hip hooray!", w: [[17.06,17.24,"hip"],[17.26,17.58,"hip"],[17.62,18.76,"hooray!"]] },
    { s: "outro", t0: 18.80, t1: 19.95, text: "(hooray!)", w: [[18.80,19.95,"(hooray!)"]] },
  ];
  const E = 'ixrleXdltsqnnrsppqhfgrsuuqrqppmgfkqikmuvxojlw00zqpprkknpojeemwvwmjkrtqprrsstsopotroeUXl0410z0221yz15750zz1445212232211257545531232112540yyz013212256554411212334542388961022012xuuwwxzz01221zyyyxzyvuvwvx1222212122221122222223221ulcZWVUWWXXZYYZabaZfpxxtqoonnnnnnnmmmmmllkjigfecaXTLE';
  const V = '+9840pjeYWVGAAAAAAINX057210w0u153yrlppoz66+1poqvur16441tePSNfy2ucMu4tbp86vZp01cRm215vjbZbj275qWUQQIrs+7ztqqrcLk6984hv0129/776jZUUPN46/+6694+888995vmaWR7/+xwokmjiqz31ijefjk23wVKHEAins97535443i4/5ubSRKCz5851jkogjd11zuguz0oq013wtz2zssuxwlep00lhx053uiZVOKJKJFHDBASsx134664663853378220yuvvz231z551zz989+8+010344334umu47665781vq02233455545574576vux4673v766wx662n5643iyy20yw732fkz11p446gUn4z5666556555435440vqpoprlcWTT4/93zdfbHr44778545yu8/6qf747wRw48893333s01zur072io03887131328//94765y0102spghjgr7tkkm50qSZhw51lnrvtxu075rVZZfcu323dMMFNg855w12330v6+43757998679++98++/6yzrqu11siihbXkou2ngv5433vXVUUvxvtyxjeVXXSEHRLPUQJQNJIDBAAAAAAAAAAAAAAAAAAAAGBEJIKDBAAAAAAAAAAAAAAAAAAAAAAAAACJKHKEGGBCQNMFGBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
  const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const dec = (s) => { const a = new Float32Array(s.length); for (let i = 0; i < s.length; i++) a[i] = B.indexOf(s[i]) / 63; return a; };
  const ENERGY = dec(E), VOCAL = dec(V);
  const sample = (arr, fps, t) => {
    const x = t * fps, i = Math.floor(x), f = x - i;
    if (i < 0) return arr[0];
    if (i >= arr.length - 1) return arr[arr.length - 1];
    return arr[i] * (1 - f) + arr[i + 1] * f;
  };
  RV.energy = (t) => sample(ENERGY, 10, t);   // overall loudness 0..1
  RV.vocal = (t) => sample(VOCAL, 30, t);     // lead vocal level 0..1 (drives lip-sync)
})(globalThis.RV);
