"""Build src/timing.js from the aligned lyrics + audio envelopes.

usage: python make_timing.py lyrics.json song.wav vocals.wav ../../src/timing.js
"""
import json, sys
import numpy as np
import soundfile as sf

LYR, SONG, VOC, OUT = sys.argv[1:5]
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"


def mono(path):
    y, sr = sf.read(path, always_2d=True)
    return y.mean(axis=1), sr


def env(y, sr, fps, lo_db, smooth=1):
    hop = int(sr / fps)
    n = len(y) // hop
    r = np.sqrt(np.mean(y[: n * hop].reshape(n, hop) ** 2, axis=1) + 1e-12)
    db = 20 * np.log10(r)
    top = np.percentile(db, 99.5)
    v = np.clip((db - lo_db - (top - 0)) / (-lo_db), 0, 1) if False else np.clip((db - (top + lo_db)) / (-lo_db), 0, 1)
    if smooth > 1:
        k = np.ones(smooth) / smooth
        v = np.convolve(v, k, mode="same")
    return v


def enc(v):
    return "".join(B64[int(round(x * 63))] for x in v)


y, sr = mono(SONG)
energy = env(y, sr, 10, -30, smooth=3)
v, vsr = mono(VOC)
vocal = env(v, vsr, 30, -32, smooth=1)

lyrics = json.load(open(LYR))
dur = len(y) / sr

with open(OUT, "w") as f:
    f.write("/* Generated by tools/analysis/make_timing.py — do not edit by hand.\n")
    f.write(" * Word timings: Whisper (large-v3-turbo) on a Demucs vocal stem, aligned to the lyric sheet.\n")
    f.write(" */\n(function (RV) {\n  'use strict';\n")
    f.write(f"  RV.DURATION = {dur:.3f};\n")
    f.write("  RV.LYRICS = [\n")
    for L in lyrics:
        words = ",".join(f"[{a:.2f},{b:.2f},{json.dumps(w)}]" for a, b, w in L["words"])
        f.write(f"    {{ s: {json.dumps(L['section'])}, t0: {L['t0']:.2f}, t1: {L['t1']:.2f}, text: {json.dumps(L['text'])}, w: [{words}] }},\n")
    f.write("  ];\n")
    f.write(f"  const E = '{enc(energy)}';\n")
    f.write(f"  const V = '{enc(vocal)}';\n")
    f.write("""  const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const dec = (s) => { const a = new Float32Array(s.length); for (let i = 0; i < s.length; i++) a[i] = B.indexOf(s[i]) / 63; return a; };
  const ENERGY = dec(E), VOCAL = dec(V);
  const sample = (arr, fps, t) => {
    const x = t * fps, i = Math.floor(x), f = x - i;
    if (i < 0) return arr[0];
    if (i >= arr.length - 1) return arr[arr.length - 1];
    return arr[i] * (1 - f) + arr[i + 1] * f;
  };
  RV.energy = (t) => sample(ENERGY, 10, t);   // overall loudness 0..1
  RV.vocal = (t) => sample(VOCAL, 30, t);     // lead vocal level 0..1 (drives lip-sync)
})(globalThis.RV);
""")
print("wrote", OUT, "duration", dur, "energy", len(energy), "vocal", len(vocal))
