/* Generated by tools/analysis/make_timing.py — do not edit by hand.
 * Word timings: Whisper (large-v3-turbo) on a Demucs vocal stem, checked by hand (tools/analysis/lyrics.json).
 */
(function (RV) {
  'use strict';
  RV.DURATION = 20.000;
  RV.LYRICS = [
    { s: "intro", t0: 0.02, t1: 1.19, text: "I'm Ben! Ben! Ben! Ben!", w: [[0.02,0.15,"I'm"],[0.17,0.40,"Ben!"],[0.45,0.65,"Ben!"],[0.74,0.97,"Ben!"],[1.02,1.19,"Ben!"]] },
    { s: "chorus1", t0: 1.21, t1: 2.40, text: "I'm Ben I'm Ben I'm Ben I'm Ben", w: [[1.21,1.42,"I'm"],[1.44,1.56,"Ben"],[1.58,1.71,"I'm"],[1.72,1.84,"Ben"],[1.86,1.99,"I'm"],[2.00,2.10,"Ben"],[2.12,2.27,"I'm"],[2.28,2.40,"Ben"]] },
    { s: "chorus1", t0: 2.44, t1: 3.52, text: "And when I'm done I'll go again", w: [[2.44,2.52,"And"],[2.52,2.68,"when"],[2.68,2.82,"I'm"],[2.82,2.94,"done"],[2.94,3.10,"I'll"],[3.10,3.24,"go"],[3.24,3.52,"again"]] },
    { s: "chorus1", t0: 3.60, t1: 4.74, text: "'Cause I'm Ben, yes I'm Ben", w: [[3.60,3.70,"'Cause"],[3.70,4.00,"I'm"],[4.00,4.16,"Ben,"],[4.26,4.40,"yes"],[4.40,4.58,"I'm"],[4.58,4.74,"Ben"]] },
    { s: "verse", t0: 4.80, t1: 5.83, text: "Where I'll go I do not know", w: [[4.80,4.96,"Where"],[4.96,5.10,"I'll"],[5.10,5.21,"go"],[5.22,5.36,"I"],[5.36,5.50,"do"],[5.50,5.64,"not"],[5.64,5.83,"know,"]] },
    { s: "verse", t0: 5.92, t1: 7.08, text: "I don't see where I could be", w: [[5.92,5.97,"I"],[5.97,6.12,"don't"],[6.12,6.22,"see"],[6.22,6.45,"where"],[6.46,6.62,"I"],[6.62,6.78,"could"],[6.79,7.08,"be,"]] },
    { s: "but", t0: 7.12, t1: 8.05, text: "bu-u-u-ut", w: [[7.12,8.05,"bu-u-u-ut"]] },
    { s: "verse", t0: 8.10, t1: 9.02, text: "I'm Ben, yes I'm Ben", w: [[8.10,8.23,"I'm"],[8.23,8.55,"Ben,"],[8.56,8.66,"yes"],[8.66,8.80,"I'm"],[8.81,9.02,"Ben"]] },
    { s: "chorus2", t0: 9.06, t1: 11.28, text: "I'm Ben I'm Ben I'm Ben I'm Ben", w: [[9.06,9.33,"I'm"],[9.34,9.60,"Ben"],[9.62,9.89,"I'm"],[9.90,10.18,"Ben"],[10.20,10.47,"I'm"],[10.48,10.74,"Ben"],[10.76,11.01,"I'm"],[11.02,11.28,"Ben"]] },
    { s: "chorus2", t0: 11.32, t1: 14.18, text: "And when I'm done I'll go again", w: [[11.32,11.53,"And"],[11.54,11.71,"when"],[11.72,12.05,"I'm"],[12.06,12.33,"done"],[12.34,12.65,"I'll"],[12.66,12.89,"go"],[12.90,14.18,"again"]] },
    { s: "finale", t0: 14.60, t1: 18.75, text: "Because, I'm, beeeeennnnn", w: [[14.60,14.96,"Because,"],[14.98,15.56,"I'm,"],[15.58,18.75,"beeeeennnnn"]] },
  ];
  const E = 'hxxy0yzxyyzwwx0zzzyzzyxwz022112211100234341101233333312122443444431222211zz000100zzyzxwy11zz2331yy031zz0233zz13321123322012432223410031121112111yyz2222221y03++++++++++8645544444432111111xtiot6666542we';
  const V = 't+7rV+8ygTAAAG97wPAAAA173nXAAAi66tcANPr95sfz82r84vle53sy+zsa36yv85wjj64sv632c536w81oOi45wy55pVz7tv5rn/850tzjw4v244751oog4756tsu360sty5zqo5673uxxy764zy31nv45x2573gw012556mn54742963w141tx20y72553545463Zp3ygg665433iBs750310z4732465446/56z8695416+753x74552257752zy08zsn67x44yhTZbL22xxx+71221nIHameq50xh+/7w1okSOXiWu3rmg99zy2vFCXchL1yzfz/52wriFFXjng6z1u353t533323zurumRFs35351u23223230ULs434408z1z0uPPw123y00002121y1011212x000zyyzyx000yzxukoqs20eqz1223zwkq433746431201vtspdx132342302311222111112111201122y11x048989++///+/+++++9+++99+9++9999988887686668766767786677763mm0xgFEAGMWWYWYVRNJCAAAAAAAAAAAAAAAAAA';
  const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const dec = (s) => { const a = new Float32Array(s.length); for (let i = 0; i < s.length; i++) a[i] = B.indexOf(s[i]) / 63; return a; };
  const ENERGY = dec(E), VOCAL = dec(V);
  const sample = (arr, fps, t) => {
    const x = t * fps, i = Math.floor(x), f = x - i;
    if (i < 0) return arr[0];
    if (i >= arr.length - 1) return arr[arr.length - 1];
    return arr[i] * (1 - f) + arr[i + 1] * f;
  };
  RV.energy = (t) => sample(ENERGY, 10, t);   // overall loudness 0..1
  RV.vocal = (t) => sample(VOCAL, 30, t);     // lead vocal level 0..1 (drives lip-sync)
})(globalThis.RV);
