/* Generated by tools/analysis/make_timing.py — do not edit by hand.
 * Word timings: Whisper (large-v3-turbo) on a Demucs vocal stem, checked by hand (tools/analysis/lyrics.json).
 */
(function (RV) {
  'use strict';
  RV.DURATION = 54.160;
  RV.LYRICS = [
    { s: "intro", t0: 0.10, t1: 0.66, text: "Ben be like,", w: [[0.10,0.30,"Ben"],[0.30,0.42,"be"],[0.42,0.66,"like,"]] },
    { s: "quote", t0: 2.48, t1: 3.36, text: "I'm not obsessed,", w: [[2.48,2.62,"I'm"],[2.62,2.80,"not"],[2.80,3.36,"obsessed,"]] },
    { s: "quote", t0: 4.80, t1: 5.82, text: "I just really like teeth!", w: [[4.80,4.90,"I"],[4.90,5.04,"just"],[5.04,5.24,"really"],[5.24,5.46,"like"],[5.46,5.82,"teeth!"]] },
    { s: "chorus", t0: 6.15, t1: 11.92, text: "(he likes teeth, oooooooh, he likes teeth)", w: [[6.15,6.48,"(he"],[6.48,6.88,"likes"],[6.88,7.85,"teeth,"],[8.55,10.95,"oooooooh,"],[11.10,11.24,"he"],[11.24,11.48,"likes"],[11.48,11.92,"teeth)"]] },
    { s: "rap", t0: 13.60, t1: 14.32, text: "Rap time!", w: [[13.60,13.85,"Rap"],[13.88,14.32,"time!"]] },
    { s: "rap", t0: 14.52, t1: 17.42, text: "He's sitting in his tooth suit on a lazy Sunday morning", w: [[14.52,14.85,"He's"],[14.85,15.15,"sitting"],[15.15,15.26,"in"],[15.26,15.48,"his"],[15.50,15.80,"tooth"],[15.80,16.02,"suit"],[16.02,16.12,"on"],[16.12,16.26,"a"],[16.26,16.70,"lazy"],[16.70,17.10,"Sunday"],[17.10,17.42,"morning"]] },
    { s: "rap", t0: 17.42, t1: 19.30, text: "admiring his collection of human teeth!", w: [[17.42,17.82,"admiring"],[17.82,17.92,"his"],[17.92,18.40,"collection"],[18.40,18.52,"of"],[18.52,18.84,"human"],[18.84,19.30,"teeth!"]] },
    { s: "what", t0: 19.74, t1: 21.15, text: "Everyone be like what what!?", w: [[19.74,20.14,"Everyone"],[20.14,20.30,"be"],[20.30,20.52,"like"],[20.55,20.78,"what"],[20.90,21.15,"what!?"]] },
    { s: "what", t0: 21.28, t1: 22.62, text: "Everyone be like what what?!", w: [[21.28,21.62,"Everyone"],[21.62,21.86,"be"],[21.86,22.05,"like"],[22.08,22.30,"what"],[22.40,22.62,"what?!"]] },
    { s: "fairy", t0: 22.66, t1: 24.95, text: "And then Ben admitted that he was a tooth fairy!", w: [[22.66,22.76,"And"],[22.76,22.94,"then"],[22.94,23.10,"Ben"],[23.10,23.52,"admitted"],[23.52,23.66,"that"],[23.66,23.78,"he"],[23.78,23.90,"was"],[23.90,24.06,"a"],[24.06,24.40,"tooth"],[24.40,24.95,"fairy!"]] },
    { s: "night", t0: 25.15, t1: 28.42, text: "He snuck into the children's houses at night that right!", w: [[25.15,25.40,"He"],[25.40,25.86,"snuck"],[25.86,26.24,"into"],[26.24,26.40,"the"],[26.40,26.92,"children's"],[26.92,27.38,"houses"],[27.38,27.56,"at"],[27.56,27.75,"night"],[27.75,27.95,"that"],[27.95,28.42,"right!"]] },
    { s: "night", t0: 28.72, t1: 31.00, text: "He took away all their teeth and gave them money!?", w: [[28.72,28.88,"He"],[28.88,29.05,"took"],[29.05,29.32,"away"],[29.32,29.50,"all"],[29.50,29.70,"their"],[29.70,29.98,"teeth"],[29.98,30.18,"and"],[30.18,30.40,"gave"],[30.40,30.60,"them"],[30.60,31.00,"money!?"]] },
    { s: "obsessed", t0: 31.00, t1: 37.30, text: "(Maybe he is obsessed after all)", w: [[31.00,32.55,"(Maybe"],[32.58,33.52,"he"],[33.52,34.12,"is"],[34.14,35.20,"obsessed"],[35.20,36.10,"after"],[36.10,37.30,"all)"]] },
    { s: "end", t0: 37.66, t1: 39.70, text: "Theeeeeeee, END!!!", w: [[37.66,39.18,"Theeeeeeee,"],[39.20,39.70,"END!!!"]] },
    { s: "outro", t0: 40.20, t1: 50.30, text: "(He likes teeth, oooooooh...)", w: [[40.20,40.36,"(He"],[40.36,40.95,"likes"],[41.10,41.56,"teeth,"],[41.56,50.30,"oooooooh...)"]] },
  ];
  const E = 'PcjnofROYlnmlkjihgfedcaadkqpmljgZVSROINWijiihgfhjkklniffgcYWWXaeffdbbfknmlljhggffecbaceghhhiikkkihhilnonlkjiihgjkhaZejYONXeghjihebeqvtqy2vqrxwrlrxzpsv5zxmnqsnnr115zyw11yvwxwvqwy0uxz6yuosvuoknx14yxv00ywxwvtvsmms414xzrusvnqpmlr30z13yvvvtrsz1tmmnfelutnkfhebgtyut02vuqrnory1xsyx2wxrtuppnvy361xw02zyxunonwvyszx3zzppmmhiovuqjlkllliiikjiijihgggghgfghhgfffilmljihgghhgffggffedcaYXWUTTcltttuvuuuuutsrqsuxtiYLGAGTgnpplgkv555553200z00320vzy4xwrtutsswz42zvxzyuuutrstxvvqvuzssnppnmlpqvwuoprqllmmkkkpnmgnnskhbddaYXejrpmhjllefeebbchfeYffkbYTWWSQPUVVLEAAAAA';
  const V = 'iQKOuyywxtyrv663wsaXSNSOPFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcpny036202jhrrow6sobnnmmbKBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAq1bpvsocjxr01ryythQLFnqhtwsncNFHGFAAAAAAAAPZnporqppnkopppihjZWgkXdhdmoknkjikopjkhfcbbZaalfeaWabbbebTSOKLJKACAAAAAIjnignkmroqqqpqmnksvvusqpozxvtqspsrnnrfstqqrwwmqwvwrpprompmmmokihjqsnhmkijghlhlt3zxteTgnjLZqjx0wxyqcOPKNRdoprrsrpqrpswvvuwutqpnowtrjiWhkdXWQdmronklpnphr97654pehqou35666565sgUKMSXYMY/6zrsqnno50vx12th11qy0xsqnSAfb7542fjopq575v97n13zpmx5543zpx42rinp661hy56xohy6+/9yw6xu76tlu54255zx3sv1soHg6404z22jrs0wu8pTAP376wt4xmLUqm586y52bSpy210z01zwuso23lz10695qic435w5+83ddq+//92pXYjtx/////6svyxrywxu4v4984iYdy34u386vXio//991aRUjsu659+/675u33seYd4882s44ZQaz64y40Xx72rv92w8tk13SJFksp6/65ugffcbm/67445z335xqsqsssronsywpiaXmhcYMSespkjij42yoppj486olz3sVept2fn4rjuzv865tWo3wnvur5885rhkmupio52ogq663oNS182uHJu+745tiNKAAACGFAAR78Zmr5yNQv3o396218796tT354pRVpph762hSUu3olgp5862sTV53qttp58+5tw1wiZcslpmopqrppprtsprspqppqppnknnqqtsrpnrttptssolYdZoumtvpmvnaittnfqrturqmZcsqmqqlkihosmnlnplljhhfivuompnmqpjgjbQUiklmmkibepkmjifeeZSQcfeecZULAAAFVoolkkdVUYYOeXmpncnmmkikhgefhhhccYacccYVSRQKLNGDACAAAAAAABh44433233343354355565544345454444521100zz1011wvy26899786764wmaebZegSNMPKHGDEXgjn2w1xyxz0xy31v1qrjmmlcfUlpw1yuyxqrplmmmtyyxsphgddceeddZeWUUTabdcbbYfaUdZXbUPTZgjdSbfmgkjkoeolXfjrropspnropmorighmnomfhfljhfgffgXdkggfgmiikhVXdgfiidWRTSQRKQGCGFDAHAACDLHJMOUZQRWWdVYTZdVddSUTehdehdcfbeXeeYYWacaWZSSVWUURTVXSUbUWVWcZWaYPITVWYYUOLLNPKHFBAAAAAAAAAACABGJSVNOSRZQUPVVTaXGRWbZZacaWaYbTbdVSWUSXSSPORRPPNMLSKNTOSNOSMNSROPPNQSSMJFHIMJIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
  const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const dec = (s) => { const a = new Float32Array(s.length); for (let i = 0; i < s.length; i++) a[i] = B.indexOf(s[i]) / 63; return a; };
  const ENERGY = dec(E), VOCAL = dec(V);
  const sample = (arr, fps, t) => {
    const x = t * fps, i = Math.floor(x), f = x - i;
    if (i < 0) return arr[0];
    if (i >= arr.length - 1) return arr[arr.length - 1];
    return arr[i] * (1 - f) + arr[i + 1] * f;
  };
  RV.energy = (t) => sample(ENERGY, 10, t);   // overall loudness 0..1
  RV.vocal = (t) => sample(VOCAL, 30, t);     // lead vocal level 0..1 (drives lip-sync)
})(globalThis.RV);
