"""timing/lines.json -> src/data/timing.js (ES module the film page imports)."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
lines = json.load(open(ROOT / "timing/lines.json"))
slim = [{"i": l["i"], "text": l["text"], "s": l["start"], "e": l["end"],
         "w": [[w["w"], w["s"], w["e"]] for w in l["words"]]} for l in lines]
(ROOT / "src/data/timing.js").write_text(
    "// generated by tools/make_timing.py — audio-time (seconds) for each script line and word\n"
    "export const LINES = " + json.dumps(slim, ensure_ascii=False) + ";\n"
    "export const AUDIO_DURATION = 152.64;\n")
print("wrote src/data/timing.js,", len(slim), "lines")
